keys:
  - &homemanager age1u8t90aryujqlerzed922kxew9hgafrvlz722myeqwyzghuvk34jqvw3pwj
  - &nixos age1m49xmzamc56p4eyz3udjzpgat9ugtywjrymp5dztyv3tk9j4tgss26ngue
creation_rules:
  - path_regex: secrets/homemanager.yaml$
    key_groups:
      - age:
        - *homemanager
  - path_regex: secrets/nixos.yaml$
    key_groups:
      - age:
        - *nixos
